# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Golfer.create(first_name: "JT", last_name: "Brennemen", email: "jtbrenneman@bailey-weiler.com", is_active: true, nickname: "JT")
Golfer.create(first_name: "Randy", last_name: "Brennemen", email: "randybrenneman@yahoo.com", is_active: true)
Golfer.create(first_name: "Bob", last_name: "Corbin", email: "bcorbin@mdlogistics.com", is_active: true)
Golfer.create(first_name: "Duane", last_name: "Dale", email: "dbld56@gmail.com", is_active: true, nickname: "Double D")
Golfer.create(first_name: "Dan", last_name: "Deaton", email: "dan.deaton@cvscaremark.com", is_active: true)
Golfer.create(first_name: "Kevin", last_name: "Deaton", email: "deatonkevin22@yahoo.com", is_active: true)
Golfer.create(first_name: "Brian", last_name: "Davidson", email: "rodie5@sbcglobal.net", is_active: true, nickname: "Rodie", phone: "317.437.1003")
Golfer.create(first_name: "Greg", last_name: "Davidson", email: "gmdavidson62@gmail.com", is_active: true, nickname: "Guido", phone: "317.965.9437")
Golfer.create(first_name: "Mike", last_name: "Davidson", email: "micoach@sbcglobal.net", is_active: true, nickname: "Coach", phone: "317.590.2080")
Golfer.create(first_name: "Don", last_name: "DuVall", email: "dduvall5@gmail.com", is_active: true)
Golfer.create(first_name: "Scott", last_name: "Eakins", email: "s.eakins@comcast.net", is_active: true)
Golfer.create(first_name: "Lenny", last_name: "Fulkerson", email: "lfulkerson67@gmail.com", is_active: true)
Golfer.create(first_name: "Todd", last_name: "Hacker", email: "pth2020@aol.com", is_active: true, nickname: "Hacker")
Golfer.create(first_name: "Dave", last_name: "Harris", email: "dhdaveharris@aol.com", is_active: true)
Golfer.create(first_name: "Mike", last_name: "Hawkins", email: "mike_hawkins@comcast.net", is_active: true, nickname: "Hawk", phone: "317.847.4530")
Golfer.create(first_name: "Mike", last_name: "Hopkins", email: "mkmrhop61@gmail.com", is_active: true, nickname: "Hoppy")
Golfer.create(first_name: "Paul", last_name: "Hunt", email: "huntwallbo@aol.com", is_active: true, nickname: "Wally")
Golfer.create(first_name: "Dan", last_name: "Johnson", email: "dij220@live.com", is_active: true, nickname: "DJ", phone: "260.894.0483")
Golfer.create(first_name: "Mark", last_name: "Kivett", email: "kivdawg1@gmail.com", is_active: true, nickname: "Kiv Dawg")
Golfer.create(first_name: "Greg", last_name: "LeBeau", email: "g.lebeau@mqautomation.com", is_active: true)
Golfer.create(first_name: "Jim", last_name: "McCallie", email: "jmccallie@hedgeright.com", is_active: true, nickname: "Jimmie Mac")
Golfer.create(first_name: "Daniel", last_name: "Morrison", email: "mojoindy1949@gmail.com", is_active: true)
Golfer.create(first_name: "Mike", last_name: "Norton", email: "norton@secure.norton.com", is_active: true, nickname: "Norty")
Golfer.create(first_name: "Jeff", last_name: "Obenchain", email: "cyberhog1@aol.com", is_active: true)
Golfer.create(first_name: "John", last_name: "Rupp", email: "ruppjohn96@yahoo.com", is_active: true, nickname: "Rupp")
Golfer.create(first_name: "John", last_name: "Schneider", email: "ejsll@yahoo.com", is_active: true, nickname: "Schneider")
Golfer.create(first_name: "Rodney", last_name: "Scott", email: "rscott6536@aol.com", is_active: true, nickname: "Hot Rod")
Golfer.create(first_name: "Phil", last_name: "Sergi", email: "phillinda0711@gmail.com", is_active: true, nickname: "Sergi")
Golfer.create(first_name: "Jim", last_name: "Sides", email: "dfsides@gmail.com", is_active: true, nickname: "Jimmy Sides")
Golfer.create(first_name: "Randy", last_name: "Sides", email: "sleerr82@gmail.com", is_active: true, nickname: "RBS")
Golfer.create(first_name: "Dan", last_name: "Sitton", email: "daniel.sitton@covance.com", is_active: true, nickname: "Pops")
Golfer.create(first_name: "Collin", last_name: "Steele", email: "steelman5000@gmail.com", is_active: true)
Golfer.create(first_name: "Jeremiah", last_name: "Stump", email: "stumpy224@gmail.com", is_active: true, nickname: "Stumpy", phone: "317.605.2588")
Golfer.create(first_name: "Scott", last_name: "Troxell", email: "ta25@msn.com", is_active: true)
Golfer.create(first_name: "Rick", last_name: "Wheeler", email: "rwheeler@flutesinc.com", is_active: true, nickname: "Wheels")
Golfer.create(first_name: "Allen", last_name: "Yeagle", email: "minisprint@hotmail.com", is_active: true)
