AdminControl.create(name: 'site_maintenance', description: 'ON = site will be unavailable and users will see a maintenance page; OFF = site will function as normal', value: 'OFF')
AdminControl.create(name: 'team_generation_emails', description: 'ON = after teams are generated and /admin/outings/:id/teams/:team_date/email is called, registered users will receive an email; OFF = emails will not be sent', value: 'ON')

david_amberger = Golfer.create(first_name: "David", last_name: "Amberger", email: "tntamberger@att.net", is_active: true, nickname: "Preacher")
bob_blackedge = Golfer.create(first_name: "Bob", last_name: "Blackedge", email: "xstixhdx@aol.com", is_active: false, nickname: "Sticks")
jt_brennemen = Golfer.create(first_name: "JT", last_name: "Brennemen", email: "jtbrenneman@bailey-weiler.com", is_active: true, nickname: "JT")
randy_brennemen = Golfer.create(first_name: "Randy", last_name: "Brennemen", email: "randybrenneman@yahoo.com", is_active: true)
bob_corbin = Golfer.create(first_name: "Bob", last_name: "Corbin", email: "bcorbin@mdlogistics.com", is_active: true)
duane_dale = Golfer.create(first_name: "Duane", last_name: "Dale", email: "dbld56@gmail.com", is_active: true, nickname: "Double D")
dan_deaton = Golfer.create(first_name: "Dan", last_name: "Deaton", email: "dan.deaton@cvscaremark.com", is_active: true)
kevin_deaton = Golfer.create(first_name: "Kevin", last_name: "Deaton", email: "deatonkevin22@yahoo.com", is_active: true)
brian_davidson = Golfer.create(first_name: "Brian", last_name: "Davidson", email: "rodie5@sbcglobal.net", is_active: true, nickname: "Rodie", phone: "317.437.1003")
greg_davidson = Golfer.create(first_name: "Greg", last_name: "Davidson", email: "gmdavidson62@gmail.com", is_active: true, nickname: "Guido", phone: "317.965.9437")
mike_davidson = Golfer.create(first_name: "Mike", last_name: "Davidson", email: "micoach@sbcglobal.net", is_active: true, nickname: "Coach", phone: "317.590.2080")
don_duvall = Golfer.create(first_name: "Don", last_name: "DuVall", email: "dduvall5@gmail.com", is_active: true, nickname: "Bob'n Weave")
scott_eakins = Golfer.create(first_name: "Scott", last_name: "Eakins", email: "s.eakins@comcast.net", is_active: true)
lenny_fulkerson = Golfer.create(first_name: "Lenny", last_name: "Fulkerson", email: "lfulkerson67@gmail.com", is_active: true)
todd_hacker = Golfer.create(first_name: "Todd", last_name: "Hacker", email: "pth2020@aol.com", is_active: true, nickname: "Hacker")
dave_harris = Golfer.create(first_name: "Dave", last_name: "Harris", email: "dhdaveharris@aol.com", is_active: true, nickname: "Harry")
mike_hawkins = Golfer.create(first_name: "Mike", last_name: "Hawkins", email: "mike_hawkins@comcast.net", is_active: true, nickname: "Hawk", phone: "317.847.4530")
mike_hopkins = Golfer.create(first_name: "Mike", last_name: "Hopkins", email: "mkmrhop61@gmail.com", is_active: true, nickname: "Hoppy")
paul_hunt = Golfer.create(first_name: "Paul", last_name: "Hunt", email: "huntwallbo@aol.com", is_active: true, nickname: "Wally")
dan_johnson = Golfer.create(first_name: "Dan", last_name: "Johnson", email: "dij220@live.com", is_active: true, nickname: "DJ", phone: "260.894.0483")
mark_kivett = Golfer.create(first_name: "Mark", last_name: "Kivett", email: "kivdawg1@gmail.com", is_active: true, nickname: "Kiv Dawg")
greg_lebeau = Golfer.create(first_name: "Greg", last_name: "LeBeau", email: "g.lebeau@mqautomation.com", is_active: true)
jim_mccallie = Golfer.create(first_name: "Jim", last_name: "McCallie", email: "jmccallie@hedgeright.com", is_active: true, nickname: "Jimmie Mac")
daniel_morrison = Golfer.create(first_name: "Daniel", last_name: "Morrison", email: "mojoindy1949@gmail.com", is_active: true)
mike_norton = Golfer.create(first_name: "Mike", last_name: "Norton", email: "norton@secure.norton.com", is_active: true, nickname: "Norty")
jeff_obenchain = Golfer.create(first_name: "Jeff", last_name: "Obenchain", email: "cyberhog1@aol.com", is_active: true)
dewayne_pennington = Golfer.create(first_name: "DeWayne", last_name: "Pennington", email: "dpennington3333@yahoo.com", is_active: true, nickname: "Pinto")
john_rupp = Golfer.create(first_name: "John", last_name: "Rupp", email: "ruppjohn96@yahoo.com", is_active: true, nickname: "Rupp")
john_schneider = Golfer.create(first_name: "John", last_name: "Schneider", email: "ejsll@yahoo.com", is_active: true, nickname: "Schneider")
rodney_scott = Golfer.create(first_name: "Rodney", last_name: "Scott", email: "rscott6536@aol.com", is_active: true, nickname: "Hot Rod")
phil_sergi = Golfer.create(first_name: "Phil", last_name: "Sergi", email: "phillinda0711@gmail.com", is_active: true, nickname: "Serg")
jim_sides = Golfer.create(first_name: "Jim", last_name: "Sides", email: "dfsides@gmail.com", is_active: true, nickname: "Jimmy Sides")
randy_sides = Golfer.create(first_name: "Randy", last_name: "Sides", email: "sleerr82@gmail.com", is_active: false, nickname: "RBS")
dan_sitton = Golfer.create(first_name: "Dan", last_name: "Sitton", email: "daniel.sitton@covance.com", is_active: true, nickname: "Pops")
collin_steele = Golfer.create(first_name: "Collin", last_name: "Steele", email: "steelman5000@gmail.com", is_active: true)
jeremiah_stump = Golfer.create(first_name: "Jeremiah", last_name: "Stump", email: "stumpy224@gmail.com", is_active: true, nickname: "Stumpy", phone: "317.605.2588")
scott_troxell = Golfer.create(first_name: "Scott", last_name: "Troxell", email: "ta25@msn.com", is_active: true)
rick_wheeler = Golfer.create(first_name: "Rick", last_name: "Wheeler", email: "rwheeler@flutesinc.com", is_active: true, nickname: "Wheels")
allen_yeagle = Golfer.create(first_name: "Allen", last_name: "Yeagle", email: "minisprint@hotmail.com", is_active: true)
casey_brenneman = Golfer.create(first_name: "Casey", last_name: "Brenneman", email: "caseyb19@hotmail.com", is_active: true)
wendell_cline = Golfer.create(first_name: "Wendell", last_name: "Cline", email: "wcline@vermontthreadgage.com", is_active: true)
gary_hollo = Golfer.create(first_name: "Gary", last_name: "Hollo", email: "gary_hollo@precoat.com", is_active: true)
roy_reed = Golfer.create(first_name: "Roy", last_name: "Reed", email: "roy.e.reed@gmail.com", is_active: true)
terry_williams = Golfer.create(first_name: "Terry", last_name: "Williams", email: "terry.williams@example.com", is_active: true)

lodging_type_villa = LodgingType.create(name: "Villa")

villa_1A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "01A", sort_order: 10)
villa_1B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "01B", sort_order: 20)
villa_2A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "02A", sort_order: 30)
villa_2B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "02B", sort_order: 40)
villa_3A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "03A", sort_order: 50)
villa_3B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "03B", sort_order: 60)
villa_4A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "04A", sort_order: 70)
villa_4B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "04B", sort_order: 80)
villa_5A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "05A", sort_order: 90)
villa_5B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "05B", sort_order: 100)
villa_6A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "06A", sort_order: 110)
villa_6B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "06B", sort_order: 120)
villa_7A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "07A", sort_order: 130)
villa_7B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "07B", sort_order: 140)
villa_8A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "08A", sort_order: 150)
villa_8B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "08B", sort_order: 160)
villa_9A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "09A", sort_order: 160)
villa_9B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "09B", sort_order: 170)
villa_10A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "10A", sort_order: 180)
villa_10B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "10B", sort_order: 190)
villa_11A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "11A", sort_order: 200)
villa_11B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "11B", sort_order: 210)
villa_12A = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "12A", sort_order: 220)
villa_12B = Lodging.create(lodging_type_id: lodging_type_villa.id, room: "12B", sort_order: 230)

peninsula = Course.create(name: "Peninsula Golf Resort", address: "136 Clubhouse Dr, Lancaster, KY 40444", phone: "859.548.5055", url: "https://peninsulagolfky.com")

hole_01_peninsula = Hole.create(course_id: peninsula.id, number: 1, par: 4, handicap: 7)
hole_02_peninsula = Hole.create(course_id: peninsula.id, number: 2, par: 5, handicap: 1)
hole_03_peninsula = Hole.create(course_id: peninsula.id, number: 3, par: 4, handicap: 17)
hole_04_peninsula = Hole.create(course_id: peninsula.id, number: 4, par: 3, handicap: 9)
hole_05_peninsula = Hole.create(course_id: peninsula.id, number: 5, par: 4, handicap: 11)
hole_06_peninsula = Hole.create(course_id: peninsula.id, number: 6, par: 5, handicap: 15)
hole_07_peninsula = Hole.create(course_id: peninsula.id, number: 7, par: 3, handicap: 13)
hole_08_peninsula = Hole.create(course_id: peninsula.id, number: 8, par: 4, handicap: 3)
hole_09_peninsula = Hole.create(course_id: peninsula.id, number: 9, par: 4, handicap: 5)
hole_10_peninsula = Hole.create(course_id: peninsula.id, number: 10, par: 4, handicap: 14)
hole_11_peninsula = Hole.create(course_id: peninsula.id, number: 11, par: 4, handicap: 8)
hole_12_peninsula = Hole.create(course_id: peninsula.id, number: 12, par: 4, handicap: 18)
hole_13_peninsula = Hole.create(course_id: peninsula.id, number: 13, par: 3, handicap: 12)
hole_14_peninsula = Hole.create(course_id: peninsula.id, number: 14, par: 5, handicap: 10)
hole_15_peninsula = Hole.create(course_id: peninsula.id, number: 15, par: 3, handicap: 4)
hole_16_peninsula = Hole.create(course_id: peninsula.id, number: 16, par: 4, handicap: 16)
hole_17_peninsula = Hole.create(course_id: peninsula.id, number: 17, par: 5, handicap: 6)
hole_18_peninsula = Hole.create(course_id: peninsula.id, number: 18, par: 4, handicap: 2)

# outing_peninsula_2018_sunday = Date.strptime("05/20/2018", '%m/%d/%Y')
# Outing.create(course_id: peninsula.id, name: "2018 Peninsula", start_date: outing_peninsula_2018_sunday, end_date: Date.strptime("05/23/2018", '%m/%d/%Y'))
#
# jt_brennemen_pen_2018 = OutingGolfer.create(outing_golfer_id: jt_brennemen.id, lodging_id: villa_11A.id)
# randy_brennemen_pen_2018 = OutingGolfer.create(outing_golfer_id: randy_brennemen.id, lodging_id: villa_12B.id)
# duane_dale_pen_2018 = OutingGolfer.create(outing_golfer_id: duane_dale.id, lodging_id: villa_12B.id)
# brian_davidson_pen_2018 = OutingGolfer.create(outing_golfer_id: brian_davidson.id, lodging_id: villa_10B.id)
# greg_davidson_pen_2018 = OutingGolfer.create(outing_golfer_id: greg_davidson.id, lodging_id: villa_10A.id)
# mike_davidson_pen_2018 = OutingGolfer.create(outing_golfer_id: mike_davidson.id, lodging_id: villa_9B.id)
# don_duvall_pen_2018 = OutingGolfer.create(outing_golfer_id: don_duvall.id, lodging_id: villa_11B.id)
# scott_eakins_pen_2018 = OutingGolfer.create(outing_golfer_id: scott_eakins.id, lodging_id: villa_11B.id)
# todd_hacker_pen_2018 = OutingGolfer.create(outing_golfer_id: todd_hacker.id, lodging_id: villa_12A.id)
# dave_harris_pen_2018 = OutingGolfer.create(outing_golfer_id: dave_harris.id, lodging_id: villa_10B.id)
# mike_hawkins_pen_2018 = OutingGolfer.create(outing_golfer_id: mike_hawkins.id, lodging_id: villa_10A.id)
# mike_hopkins_pen_2018 = OutingGolfer.create(outing_golfer_id: mike_hopkins.id, lodging_id: villa_11B.id)
# paul_hunt_pen_2018 = OutingGolfer.create(outing_golfer_id: paul_hunt.id, lodging_id: villa_12B.id)
# dan_johnson_pen_2018 = OutingGolfer.create(outing_golfer_id: dan_johnson.id, lodging_id: villa_10A.id)
# mark_kivett_pen_2018 = OutingGolfer.create(outing_golfer_id: mark_kivett.id, lodging_id: villa_11A.id)
# mike_norton_pen_2018 = OutingGolfer.create(outing_golfer_id: mike_norton.id, lodging_id: villa_12A.id)
# jeff_obenchain_pen_2018 = OutingGolfer.create(outing_golfer_id: jeff_obenchain.id, lodging_id: villa_12A.id)
# dewayne_pennington_pen_2018 = OutingGolfer.create(outing_golfer_id: dewayne_pennington.id, lodging_id: villa_10B.id)
# john_schneider_pen_2018 = OutingGolfer.create(outing_golfer_id: john_schneider.id, lodging_id: villa_9B.id)
# phil_sergi_pen_2018 = OutingGolfer.create(outing_golfer_id: phil_sergi.id, lodging_id: villa_12B.id)
# jim_sides_pen_2018 = OutingGolfer.create(outing_golfer_id: jim_sides.id, lodging_id: villa_9B.id)
# dan_sitton_pen_2018 = OutingGolfer.create(outing_golfer_id: dan_sitton.id, lodging_id: villa_11A.id)
# jeremiah_stump_pen_2018 = OutingGolfer.create(outing_golfer_id: jeremiah_stump.id, lodging_id: villa_10A.id)
# rick_wheeler_pen_2018 = OutingGolfer.create(outing_golfer_id: rick_wheeler.id, lodging_id: villa_11B.id)
# allen_yeagle_pen_2018 = OutingGolfer.create(outing_golfer_id: allen_yeagle.id, lodging_id: villa_12A.id)
#
# Team.create(outing_golfer_id: jt_brennemen_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 6, rank_number: 6, rank_letter: "C", points_expected: 14)
# Team.create(outing_golfer_id: randy_brennemen_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 5, rank_number: 3, rank_letter: "D", points_expected: 10)
# Team.create(outing_golfer_id: duane_dale_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 6, rank_number: 2, rank_letter: "D", points_expected: 13)
# Team.create(outing_golfer_id: brian_davidson_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 2, rank_number: 2, rank_letter: "C", points_expected: 17)
# Team.create(outing_golfer_id: greg_davidson_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 7, rank_number: 7, rank_letter: "C", points_expected: 13)
# Team.create(outing_golfer_id: mike_davidson_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 6, rank_number: 6, rank_letter: "A", points_expected: 23)
# Team.create(outing_golfer_id: don_duvall_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 2, rank_number: 2, rank_letter: "A", points_expected: 26)
# Team.create(outing_golfer_id: scott_eakins_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 1, rank_number: 7, rank_letter: "B", points_expected: 18)
# Team.create(outing_golfer_id: todd_hacker_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 3, rank_number: 5, rank_letter: "D", points_expected: 9)
# Team.create(outing_golfer_id: dave_harris_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 5, rank_number: 5, rank_letter: "A", points_expected: 24)
# Team.create(outing_golfer_id: mike_hawkins_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 3, rank_number: 5, rank_letter: "B", points_expected: 20)
# Team.create(outing_golfer_id: mike_hopkins_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 1, rank_number: 1, rank_letter: "C", points_expected: 17)
# Team.create(outing_golfer_id: paul_hunt_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 7, rank_number: 1, rank_letter: "D", points_expected: 13)
# Team.create(outing_golfer_id: dan_johnson_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 4, rank_number: 4, rank_letter: "A", points_expected: 24)
# Team.create(outing_golfer_id: mark_kivett_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 4, rank_number: 4, rank_letter: "C", points_expected: 16)
# Team.create(outing_golfer_id: mike_norton_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 2, rank_number: 6, rank_letter: "D", points_expected: 3)
# Team.create(outing_golfer_id: jeff_obenchain_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 4, rank_number: 4, rank_letter: "B", points_expected: 20)
# Team.create(outing_golfer_id: dewayne_pennington_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 1, rank_number: 1, rank_letter: "A", points_expected: 30)
# Team.create(outing_golfer_id: john_schneider_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 3, rank_number: 3, rank_letter: "A", points_expected: 24)
# Team.create(outing_golfer_id: phil_sergi_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 5, rank_number: 3, rank_letter: "B", points_expected: 21)
# Team.create(outing_golfer_id: jim_sides_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 7, rank_number: 7, rank_letter: "A", points_expected: 22)
# Team.create(outing_golfer_id: dan_sitton_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 5, rank_number: 5, rank_letter: "C", points_expected: 15)
# Team.create(outing_golfer_id: jeremiah_stump_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 2, rank_number: 6, rank_letter: "B", points_expected: 19)
# Team.create(outing_golfer_id: rick_wheeler_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 6, rank_number: 2, rank_letter: "B", points_expected: 21)
# Team.create(outing_golfer_id: allen_yeagle_pen_2018.id, team_date: outing_peninsula_2018_sunday, team_number: 7, rank_number: 1, rank_letter: "B", points_expected: 22)
