AdminUser.create(email: 'stumpy224@gmail.com', password: 'password', password_confirmation: 'password')

david_amberger = Golfer.create(first_name: "David", last_name: "Amberger", email: "tntamberger@att.net", is_active: true, nickname: "Preacher")
bob_blackedge = Golfer.create(first_name: "Bob", last_name: "Blackedge", email: "xstixhdx@aol.com", is_active: false, nickname: "Sticks")
jt_brennemen = Golfer.create(first_name: "JT", last_name: "Brennemen", email: "jtbrenneman@bailey-weiler.com", is_active: true, nickname: "JT")
randy_brennemen = Golfer.create(first_name: "Randy", last_name: "Brennemen", email: "randybrenneman@yahoo.com", is_active: true)
bob_corbin = Golfer.create(first_name: "Bob", last_name: "Corbin", email: "bcorbin@mdlogistics.com", is_active: true)
duane_dale = Golfer.create(first_name: "Duane", last_name: "Dale", email: "dbld56@gmail.com", is_active: true, nickname: "Double D")
dan_deaton = Golfer.create(first_name: "Dan", last_name: "Deaton", email: "dan.deaton@cvscaremark.com", is_active: true)
kevin_deaton = Golfer.create(first_name: "Kevin", last_name: "Deaton", email: "deatonkevin22@yahoo.com", is_active: true)
brian_davidson = Golfer.create(first_name: "Brian", last_name: "Davidson", email: "rodie5@sbcglobal.net", is_active: true, nickname: "Rodie", phone: "317.437.1003")
greg_davidson = Golfer.create(first_name: "Greg", last_name: "Davidson", email: "gmdavidson62@gmail.com", is_active: true, nickname: "Guido", phone: "317.965.9437")
mike_davidson = Golfer.create(first_name: "Mike", last_name: "Davidson", email: "micoach@sbcglobal.net", is_active: true, nickname: "Coach", phone: "317.590.2080")
don_duvall = Golfer.create(first_name: "Don", last_name: "DuVall", email: "dduvall5@gmail.com", is_active: true, nickname: "Bob'n Weave")
scott_eakins = Golfer.create(first_name: "Scott", last_name: "Eakins", email: "s.eakins@comcast.net", is_active: true)
lenny_fulkerson = Golfer.create(first_name: "Lenny", last_name: "Fulkerson", email: "lfulkerson67@gmail.com", is_active: true)
todd_hacker = Golfer.create(first_name: "Todd", last_name: "Hacker", email: "pth2020@aol.com", is_active: true, nickname: "Hacker")
dave_harris = Golfer.create(first_name: "Dave", last_name: "Harris", email: "dhdaveharris@aol.com", is_active: true, nickname: "Harry")
mike_hawkins = Golfer.create(first_name: "Mike", last_name: "Hawkins", email: "mike_hawkins@comcast.net", is_active: true, nickname: "Hawk", phone: "317.847.4530")
mike_hopkins = Golfer.create(first_name: "Mike", last_name: "Hopkins", email: "mkmrhop61@gmail.com", is_active: true, nickname: "Hoppy")
paul_hunt = Golfer.create(first_name: "Paul", last_name: "Hunt", email: "huntwallbo@aol.com", is_active: true, nickname: "Wally")
dan_johnson = Golfer.create(first_name: "Dan", last_name: "Johnson", email: "dij220@live.com", is_active: true, nickname: "DJ", phone: "260.894.0483")
mark_kivett = Golfer.create(first_name: "Mark", last_name: "Kivett", email: "kivdawg1@gmail.com", is_active: true, nickname: "Kiv Dawg")
greg_lebeau = Golfer.create(first_name: "Greg", last_name: "LeBeau", email: "g.lebeau@mqautomation.com", is_active: true)
jim_mccallie = Golfer.create(first_name: "Jim", last_name: "McCallie", email: "jmccallie@hedgeright.com", is_active: true, nickname: "Jimmie Mac")
daniel_morrison = Golfer.create(first_name: "Daniel", last_name: "Morrison", email: "mojoindy1949@gmail.com", is_active: true)
mike_norton = Golfer.create(first_name: "Mike", last_name: "Norton", email: "norton@secure.norton.com", is_active: true, nickname: "Norty")
jeff_obenchain = Golfer.create(first_name: "Jeff", last_name: "Obenchain", email: "cyberhog1@aol.com", is_active: true)
dewayne_pennington = Golfer.create(first_name: "DeWayne", last_name: "Pennington", email: "dpennington3333@yahoo.com", is_active: true, nickname: "Pinto")
john_rupp = Golfer.create(first_name: "John", last_name: "Rupp", email: "ruppjohn96@yahoo.com", is_active: true, nickname: "Rupp")
john_schneider = Golfer.create(first_name: "John", last_name: "Schneider", email: "ejsll@yahoo.com", is_active: true, nickname: "Schneider")
rodney_scott = Golfer.create(first_name: "Rodney", last_name: "Scott", email: "rscott6536@aol.com", is_active: true, nickname: "Hot Rod")
phil_sergi = Golfer.create(first_name: "Phil", last_name: "Sergi", email: "phillinda0711@gmail.com", is_active: true, nickname: "Serg")
jim_sides = Golfer.create(first_name: "Jim", last_name: "Sides", email: "dfsides@gmail.com", is_active: true, nickname: "Jimmy Sides")
randy_sides = Golfer.create(first_name: "Randy", last_name: "Sides", email: "sleerr82@gmail.com", is_active: false, nickname: "RBS")
dan_sitton = Golfer.create(first_name: "Dan", last_name: "Sitton", email: "daniel.sitton@covance.com", is_active: true, nickname: "Pops")
collin_steele = Golfer.create(first_name: "Collin", last_name: "Steele", email: "steelman5000@gmail.com", is_active: true)
jeremiah_stump = Golfer.create(first_name: "Jeremiah", last_name: "Stump", email: "stumpy224@gmail.com", is_active: true, nickname: "Stumpy", phone: "317.605.2588")
scott_troxell = Golfer.create(first_name: "Scott", last_name: "Troxell", email: "ta25@msn.com", is_active: true)
rick_wheeler = Golfer.create(first_name: "Rick", last_name: "Wheeler", email: "rwheeler@flutesinc.com", is_active: true, nickname: "Wheels")
allen_yeagle = Golfer.create(first_name: "Allen", last_name: "Yeagle", email: "minisprint@hotmail.com", is_active: true)

peninsula = Course.create(name: "Peninsula Golf Resort", address: "136 Clubhouse Dr, Lancaster, KY 40444", phone: "859.548.5055", url: "https://peninsulagolfky.com")

hole_01_peninsula = Hole.create(course_id: peninsula.id, number: 1, par: 4, handicap: 7)
hole_02_peninsula = Hole.create(course_id: peninsula.id, number: 2, par: 5, handicap: 1)
hole_03_peninsula = Hole.create(course_id: peninsula.id, number: 3, par: 4, handicap: 17)
hole_04_peninsula = Hole.create(course_id: peninsula.id, number: 4, par: 3, handicap: 9)
hole_05_peninsula = Hole.create(course_id: peninsula.id, number: 5, par: 4, handicap: 11)
hole_06_peninsula = Hole.create(course_id: peninsula.id, number: 6, par: 5, handicap: 15)
hole_07_peninsula = Hole.create(course_id: peninsula.id, number: 7, par: 3, handicap: 13)
hole_08_peninsula = Hole.create(course_id: peninsula.id, number: 8, par: 4, handicap: 3)
hole_09_peninsula = Hole.create(course_id: peninsula.id, number: 9, par: 4, handicap: 5)
hole_10_peninsula = Hole.create(course_id: peninsula.id, number: 10, par: 4, handicap: 14)
hole_11_peninsula = Hole.create(course_id: peninsula.id, number: 11, par: 4, handicap: 8)
hole_12_peninsula = Hole.create(course_id: peninsula.id, number: 12, par: 4, handicap: 18)
hole_13_peninsula = Hole.create(course_id: peninsula.id, number: 13, par: 3, handicap: 12)
hole_14_peninsula = Hole.create(course_id: peninsula.id, number: 14, par: 5, handicap: 10)
hole_15_peninsula = Hole.create(course_id: peninsula.id, number: 15, par: 3, handicap: 4)
hole_16_peninsula = Hole.create(course_id: peninsula.id, number: 16, par: 4, handicap: 16)
hole_17_peninsula = Hole.create(course_id: peninsula.id, number: 17, par: 5, handicap: 6)
hole_18_peninsula = Hole.create(course_id: peninsula.id, number: 18, par: 4, handicap: 2)

outing_peninsula_2018_sunday = Date.strptime("05/20/2018", '%m/%d/%Y')
outing_peninsula_2018_monday = Date.strptime("05/21/2018", '%m/%d/%Y')
outing_peninsula_2018_tuesday = Date.strptime("05/22/2018", '%m/%d/%Y')
outing_peninsula_2018_wednesday = Date.strptime("05/23/2018", '%m/%d/%Y')

outing_peninsula_2018 = Outing.create(course_id: peninsula.id, name: "2018 Peninsula", start_date: outing_peninsula_2018_sunday, end_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jt_brennemen.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jt_brennemen.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jt_brennemen.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jt_brennemen.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: randy_brennemen.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: randy_brennemen.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: randy_brennemen.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: randy_brennemen.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: duane_dale.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: duane_dale.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: duane_dale.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: duane_dale.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: brian_davidson.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: brian_davidson.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: brian_davidson.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: brian_davidson.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: greg_davidson.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: greg_davidson.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: greg_davidson.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: greg_davidson.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_davidson.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_davidson.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_davidson.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_davidson.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: don_duvall.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: don_duvall.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: don_duvall.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: don_duvall.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: scott_eakins.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: scott_eakins.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: scott_eakins.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: scott_eakins.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: todd_hacker.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: todd_hacker.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: todd_hacker.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: todd_hacker.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dave_harris.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dave_harris.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dave_harris.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dave_harris.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_hawkins.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_hawkins.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_hawkins.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_hawkins.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_hopkins.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_hopkins.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_hopkins.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_hopkins.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: paul_hunt.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: paul_hunt.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: paul_hunt.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: paul_hunt.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dan_johnson.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dan_johnson.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dan_johnson.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dan_johnson.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mark_kivett.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mark_kivett.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mark_kivett.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mark_kivett.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_norton.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_norton.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_norton.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: mike_norton.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jeff_obenchain.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jeff_obenchain.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jeff_obenchain.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jeff_obenchain.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dewayne_pennington.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dewayne_pennington.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dewayne_pennington.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dewayne_pennington.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: john_schneider.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: john_schneider.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: john_schneider.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: john_schneider.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: phil_sergi.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: phil_sergi.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: phil_sergi.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: phil_sergi.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jim_sides.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jim_sides.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jim_sides.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jim_sides.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dan_sitton.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dan_sitton.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dan_sitton.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: dan_sitton.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jeremiah_stump.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jeremiah_stump.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jeremiah_stump.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: jeremiah_stump.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: rick_wheeler.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: rick_wheeler.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: rick_wheeler.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: rick_wheeler.id, attend_date: outing_peninsula_2018_wednesday)

Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: allen_yeagle.id, attend_date: outing_peninsula_2018_sunday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: allen_yeagle.id, attend_date: outing_peninsula_2018_monday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: allen_yeagle.id, attend_date: outing_peninsula_2018_tuesday)
Attendee.create(outing_id: outing_peninsula_2018.id, golfer_id: allen_yeagle.id, attend_date: outing_peninsula_2018_wednesday)

# gold_tees = Tee.create(course_id: peninsula.id, name: "Gold", rating: 71.5, slope: 124)
# blue_tees = Tee.create(course_id: peninsula.id, name: "Blue", rating: 68.9, slope: 119)
# white_tees = Tee.create(course_id: peninsula.id, name: "White", rating: 68.7, slope: 117)
# red_tees = Tee.create(course_id: peninsula.id, name: "Red", rating: 68.5, slope: 115)

# Yardage.create(hole_id: hole_01.id, tee_id: gold_tees.id, yards: 425)
# Yardage.create(hole_id: hole_01.id, tee_id: blue_tees.id, yards: 392)
# Yardage.create(hole_id: hole_01.id, tee_id: white_tees.id, yards: 385)
# Yardage.create(hole_id: hole_01.id, tee_id: red_tees.id, yards: 308)
#
# Yardage.create(hole_id: hole_02.id, tee_id: gold_tees.id, yards: 575)
# Yardage.create(hole_id: hole_02.id, tee_id: blue_tees.id, yards: 538)
# Yardage.create(hole_id: hole_02.id, tee_id: white_tees.id, yards: 424)
# Yardage.create(hole_id: hole_02.id, tee_id: red_tees.id, yards: 424)
#
# Yardage.create(hole_id: hole_03.id, tee_id: gold_tees.id, yards: 299)
# Yardage.create(hole_id: hole_03.id, tee_id: blue_tees.id, yards: 284)
# Yardage.create(hole_id: hole_03.id, tee_id: white_tees.id, yards: 280)
# Yardage.create(hole_id: hole_03.id, tee_id: red_tees.id, yards: 275)
#
# Yardage.create(hole_id: hole_04.id, tee_id: gold_tees.id, yards: 185)
# Yardage.create(hole_id: hole_04.id, tee_id: blue_tees.id, yards: 144)
# Yardage.create(hole_id: hole_04.id, tee_id: white_tees.id, yards: 128)
# Yardage.create(hole_id: hole_04.id, tee_id: red_tees.id, yards: 108)
#
# Yardage.create(hole_id: hole_05.id, tee_id: gold_tees.id, yards: 393)
# Yardage.create(hole_id: hole_05.id, tee_id: blue_tees.id, yards: 373)
# Yardage.create(hole_id: hole_05.id, tee_id: white_tees.id, yards: 355)
# Yardage.create(hole_id: hole_05.id, tee_id: red_tees.id, yards: 285)
#
# Yardage.create(hole_id: hole_06.id, tee_id: gold_tees.id, yards: 476)
# Yardage.create(hole_id: hole_06.id, tee_id: blue_tees.id, yards: 466)
# Yardage.create(hole_id: hole_06.id, tee_id: white_tees.id, yards: 456)
# Yardage.create(hole_id: hole_06.id, tee_id: red_tees.id, yards: 412)
#
# Yardage.create(hole_id: hole_07.id, tee_id: gold_tees.id, yards: 191)
# Yardage.create(hole_id: hole_07.id, tee_id: blue_tees.id, yards: 170)
# Yardage.create(hole_id: hole_07.id, tee_id: white_tees.id, yards: 150)
# Yardage.create(hole_id: hole_07.id, tee_id: red_tees.id, yards: 123)
#
# Yardage.create(hole_id: hole_08.id, tee_id: gold_tees.id, yards: 366)
# Yardage.create(hole_id: hole_08.id, tee_id: blue_tees.id, yards: 354)
# Yardage.create(hole_id: hole_08.id, tee_id: white_tees.id, yards: 275)
# Yardage.create(hole_id: hole_08.id, tee_id: red_tees.id, yards: 270)
#
# Yardage.create(hole_id: hole_09.id, tee_id: gold_tees.id, yards: 423)
# Yardage.create(hole_id: hole_09.id, tee_id: blue_tees.id, yards: 378)
# Yardage.create(hole_id: hole_09.id, tee_id: white_tees.id, yards: 366)
# Yardage.create(hole_id: hole_09.id, tee_id: red_tees.id, yards: 300)
#
# Yardage.create(hole_id: hole_10.id, tee_id: gold_tees.id, yards: 349)
# Yardage.create(hole_id: hole_10.id, tee_id: blue_tees.id, yards: 309)
# Yardage.create(hole_id: hole_10.id, tee_id: white_tees.id, yards: 298)
# Yardage.create(hole_id: hole_10.id, tee_id: red_tees.id, yards: 275)
#
# Yardage.create(hole_id: hole_11.id, tee_id: gold_tees.id, yards: 378)
# Yardage.create(hole_id: hole_11.id, tee_id: blue_tees.id, yards: 329)
# Yardage.create(hole_id: hole_11.id, tee_id: white_tees.id, yards: 315)
# Yardage.create(hole_id: hole_11.id, tee_id: red_tees.id, yards: 267)
#
# Yardage.create(hole_id: hole_12.id, tee_id: gold_tees.id, yards: 305)
# Yardage.create(hole_id: hole_12.id, tee_id: blue_tees.id, yards: 298)
# Yardage.create(hole_id: hole_12.id, tee_id: white_tees.id, yards: 292)
# Yardage.create(hole_id: hole_12.id, tee_id: red_tees.id, yards: 268)
#
# Yardage.create(hole_id: hole_13.id, tee_id: gold_tees.id, yards: 166)
# Yardage.create(hole_id: hole_13.id, tee_id: blue_tees.id, yards: 157)
# Yardage.create(hole_id: hole_13.id, tee_id: white_tees.id, yards: 147)
# Yardage.create(hole_id: hole_13.id, tee_id: red_tees.id, yards: 118)
#
# Yardage.create(hole_id: hole_14.id, tee_id: gold_tees.id, yards: 540)
# Yardage.create(hole_id: hole_14.id, tee_id: blue_tees.id, yards: 494)
# Yardage.create(hole_id: hole_14.id, tee_id: white_tees.id, yards: 461)
# Yardage.create(hole_id: hole_14.id, tee_id: red_tees.id, yards: 457)
#
# Yardage.create(hole_id: hole_15.id, tee_id: gold_tees.id, yards: 211)
# Yardage.create(hole_id: hole_15.id, tee_id: blue_tees.id, yards: 166)
# Yardage.create(hole_id: hole_15.id, tee_id: white_tees.id, yards: 127)
# Yardage.create(hole_id: hole_15.id, tee_id: red_tees.id, yards: 125)
#
# Yardage.create(hole_id: hole_16.id, tee_id: gold_tees.id, yards: 332)
# Yardage.create(hole_id: hole_16.id, tee_id: blue_tees.id, yards: 308)
# Yardage.create(hole_id: hole_16.id, tee_id: white_tees.id, yards: 300)
# Yardage.create(hole_id: hole_16.id, tee_id: red_tees.id, yards: 279)
#
# Yardage.create(hole_id: hole_17.id, tee_id: gold_tees.id, yards: 568)
# Yardage.create(hole_id: hole_17.id, tee_id: blue_tees.id, yards: 501)
# Yardage.create(hole_id: hole_17.id, tee_id: white_tees.id, yards: 420)
# Yardage.create(hole_id: hole_17.id, tee_id: red_tees.id, yards: 415)
#
# Yardage.create(hole_id: hole_18.id, tee_id: gold_tees.id, yards: 465)
# Yardage.create(hole_id: hole_18.id, tee_id: blue_tees.id, yards: 421)
# Yardage.create(hole_id: hole_18.id, tee_id: white_tees.id, yards: 340)
# Yardage.create(hole_id: hole_18.id, tee_id: red_tees.id, yards: 340)
